### ISSUE TITLE
Sakushima Islanders can't go to the ocean.

### ISSUE THREAD

**Issue by Hamaguri-0414** [equal-l2/nearest-ocean#1]
I am sad.

e.g. ) 34.727960696002796, 137.03965679277874

![image](https://user-images.githubusercontent.com/70366052/172995329-a9b27227-8a87-43b3-9a72-a66d6aad11a3.png)

**Comment by equal-l2** [comment]
Currently, the coastline is simplified as shown below:
(the green line is the original and the pink line is the simplified)

<img width="499" alt="Screenshot 2022-06-10 at 16 20 10" src="https://user-images.githubusercontent.com/8597717/173012018-7063c876-9648-4397-8037-d84d4a05e013.png">

This issue should be solved just by increasing the precision of simplification.

**Comment by equal-l2** [comment]
Precision is now increased.

<img width="576" alt="Screenshot 2022-06-10 at 16 52 28" src="https://user-images.githubusercontent.com/8597717/173018011-c74f4892-82d5-4d4e-b36a-ddb3efeb128c.png">
